version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "kosp-frontend"
    IMAGE_TAG: "latest"
  exported-variables:
    - IMAGE_URI
    - IMAGE_TAG

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        set -euo pipefail
        echo "[install] 의존성 설치 중"
        npm ci

  pre_build:
    commands:
      - |
        set -euo pipefail
        echo "[pre_build] Account/Region 확인 및 ECR 로그인"
        : "${AWS_DEFAULT_REGION:?AWS_DEFAULT_REGION is required}"
        AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}"
        export AWS_ACCOUNT_ID
        ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
        aws --version
        aws ecr get-login-password --region "$AWS_DEFAULT_REGION" \
          | docker login --username AWS --password-stdin "$ECR_REGISTRY"

        echo "[pre_build] Next.js 빌드 수행"
        npm run build

        IMAGE_TAG="${IMAGE_TAG:-${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}}"
        export IMAGE_TAG
        IMAGE_URI="$ECR_REGISTRY/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
        export IMAGE_URI

  build:
    commands:
      - |
        set -euo pipefail
        echo "[build] Docker 이미지 빌드 시작: ${IMAGE_URI}"
        docker build -t "${IMAGE_URI}" .

  post_build:
    commands:
      - |
        set -euo pipefail
        echo "[post_build] Docker 이미지 푸시"
        docker push "${IMAGE_URI}"
        echo "[post_build] imageDetail.json 생성"
        printf '{"ImageURI":"%s"}' "${IMAGE_URI}" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
